
	#' Issues a command for the device to execute.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.device.chromeos
	#' }
	#' @param customerId Immutable. Immutable ID of the G Suite account.
	#' @param deviceId Immutable. Immutable ID of Chrome OS Device.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	admin.customer.devices.chromeos.issueCommand <- function(customerId = NULL, deviceId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('admin.customer.devices.chromeos.issueCommand')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}:issueCommand', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Gets command data a specific command issued to the device.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.device.chromeos
	#' \item https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
	#' }
	#' @param customerId Immutable. Immutable ID of the G Suite account.
	#' @param deviceId Immutable. Immutable ID of Chrome OS Device.
	#' @param commandId Immutable. Immutable ID of Chrome OS Device Command.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are payload, issueTime, commandId, type, state, commandResult, commandExpireTime.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	admin.customer.devices.chromeos.commands.get <- function(customerId = NULL, deviceId = NULL, commandId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('admin.customer.devices.chromeos.commands.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}/commands/{commandId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
