
	#' Deletes a building.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param buildingId The id of the building to delete.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.buildings.delete <- function(customer = NULL, buildingId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.buildings.delete')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a building.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param buildingId The unique ID of the building to retrieve.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are description, buildingName, address, etags, kind, coordinates, buildingId, floorNames.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.buildings.get <- function(customer = NULL, buildingId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.buildings.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Inserts a building.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.buildings.insert <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.buildings.insert')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'admin/directory/v1/customer/{customer}/resources/buildings', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a list of buildings for an account.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are kind, nextPageToken, buildings, etag.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.buildings.list <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.buildings.list')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/resources/buildings', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Patches a building via Apiary Patch Orchestration.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param buildingId The id of the building to update.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.buildings.patch <- function(customer = NULL, buildingId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.buildings.patch')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PATCH', path = 'admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Updates a building.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param buildingId The id of the building to update.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.buildings.update <- function(customer = NULL, buildingId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.buildings.update')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PUT', path = 'admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Deletes a calendar resource.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param calendarResourceId The unique ID of the calendar resource to delete.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.calendars.delete <- function(customer = NULL, calendarResourceId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.calendars.delete')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a calendar resource.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param calendarResourceId The unique ID of the calendar resource to retrieve.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are resourceDescription, resourceId, capacity, userVisibleDescription, featureInstances, generatedResourceName, resourceCategory, resourceName, etags, buildingId, kind, floorName, resourceType, floorSection, resourceEmail.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.calendars.get <- function(customer = NULL, calendarResourceId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.calendars.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Inserts a calendar resource.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.calendars.insert <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.calendars.insert')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'admin/directory/v1/customer/{customer}/resources/calendars', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a list of calendar resources for an account.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are etag, items, kind, nextPageToken.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.calendars.list <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.calendars.list')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/resources/calendars', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Patches a calendar resource via Apiary Patch Orchestration.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param calendarResourceId The unique ID of the calendar resource to update.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.calendars.patch <- function(customer = NULL, calendarResourceId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.calendars.patch')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PATCH', path = 'admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Updates a calendar resource. This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param calendarResourceId The unique ID of the calendar resource to update.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.calendars.update <- function(customer = NULL, calendarResourceId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.calendars.update')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PUT', path = 'admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Deletes a feature.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param featureKey The unique ID of the feature to delete.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.delete <- function(customer = NULL, featureKey = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.delete')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'admin/directory/v1/customer/{customer}/resources/features/{featureKey}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a feature.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param featureKey The unique ID of the feature to retrieve.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are kind, etags, name.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.get <- function(customer = NULL, featureKey = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/resources/features/{featureKey}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Inserts a feature.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.insert <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.insert')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'admin/directory/v1/customer/{customer}/resources/features', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a list of features for an account.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are nextPageToken, features, etag, kind.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.list <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.list')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/resources/features', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Patches a feature via Apiary Patch Orchestration.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param featureKey The unique ID of the feature to update.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.patch <- function(customer = NULL, featureKey = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.patch')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PATCH', path = 'admin/directory/v1/customer/{customer}/resources/features/{featureKey}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Renames a feature.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param oldName The unique ID of the feature to rename.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.rename <- function(customer = NULL, oldName = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.rename')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'admin/directory/v1/customer/{customer}/resources/features/{oldName}/rename', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Updates a feature.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.resource.calendar
	#' }
	#' @param customer The unique ID for the customer's G Suite account. As an account administrator, you can also use the `my_customer` alias to represent your account's customer ID.
	#' @param featureKey The unique ID of the feature to update.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.resources.features.update <- function(customer = NULL, featureKey = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.resources.features.update')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PUT', path = 'admin/directory/v1/customer/{customer}/resources/features/{featureKey}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
