
	#' Deletes a role.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param roleId Immutable ID of the role.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.roles.delete <- function(customer = NULL, roleId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.roles.delete')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'admin/directory/v1/customer/{customer}/roles/{roleId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a role.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param roleId Immutable ID of the role.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are etag, isSuperAdminRole, roleDescription, kind, roleId, roleName, rolePrivileges, isSystemRole.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.roles.get <- function(customer = NULL, roleId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.roles.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/roles/{roleId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Creates a role.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.roles.insert <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.roles.insert')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'admin/directory/v1/customer/{customer}/roles', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a paginated list of all the roles in a domain.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are items, etag, kind, nextPageToken.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.roles.list <- function(customer = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.roles.list')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'admin/directory/v1/customer/{customer}/roles', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Patch role via Apiary Patch Orchestration
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param roleId Immutable ID of the role.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.roles.patch <- function(customer = NULL, roleId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.roles.patch')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PATCH', path = 'admin/directory/v1/customer/{customer}/roles/{roleId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Updates a role.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param roleId Immutable ID of the role.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	directory.roles.update <- function(customer = NULL, roleId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('directory.roles.update')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PUT', path = 'admin/directory/v1/customer/{customer}/roles/{roleId}', params = params, body = NULL, token = token, base_url = 'https://admin.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
