
	#' Stop watching resources through this channel.
	#'
	#'  Autogenerated via \code{\link[googlePackageMaker]{package_make}}.
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.user
	#' \item https://www.googleapis.com/auth/admin.directory.user.alias
	#' \item https://www.googleapis.com/auth/admin.directory.user.alias.readonly
	#' \item https://www.googleapis.com/auth/admin.directory.user.readonly
	#' \item https://www.googleapis.com/auth/cloud-platform
	#' }
	#' @param params Additional parameters controlling delivery channel behavior. Optional.
	#' @param token An arbitrary string delivered to the target address with each notification delivered over this channel. Optional.
	#' @param payload A Boolean value to indicate whether payload is wanted. Optional.
	#' @param resourceId An opaque ID that identifies the resource being watched on this channel. Stable across different API versions.
	#' @param type The type of delivery mechanism used for this channel.
	#' @param expiration Date and time of notification channel expiration, expressed as a Unix timestamp, in milliseconds. Optional.
	#' @param id A UUID or similar unique string that identifies this channel.
	#' @param resourceUri A version-specific identifier for the watched resource.
	#' @param address The address where notifications are delivered for this channel.
	#' @param kind Identifies this as a notification channel used to watch for changes to a resource, which is `api#channel`.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	channels.stop <- function(params = NULL, token = NULL, payload = NULL, resourceId = NULL, type = NULL, expiration = NULL, id = NULL, resourceUri = NULL, address = NULL, kind = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['admin.channels.stop']]$scopes), return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['admin.channels.stop']], params = params, base_url = 'https://admin.googleapis.com/')
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token), base_url = req$base_url)
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
