
	#' Deletes a role assignment.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{make_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param roleAssignmentId Immutable ID of the role assignment.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	roleAssignments.delete <- function(customer, roleAssignmentId, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.roleAssignments.delete']]$scopes), return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.roleAssignments.delete']], params = params)
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token))
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieve a role assignment.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{make_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param roleAssignmentId Immutable ID of the role assignment.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	roleAssignments.get <- function(customer, roleAssignmentId, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.roleAssignments.get']]$scopes), return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.roleAssignments.get']], params = params)
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token))
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Creates a role assignment.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{make_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param assignedTo The unique ID of the user this role is assigned to.
	#' @param kind The type of the API resource. This is always `admin#directory#roleAssignment`.
	#' @param etag ETag of the resource.
	#' @param roleAssignmentId ID of this roleAssignment.
	#' @param scopeType The scope in which this role is assigned.
	#' @param orgUnitId If the role is restricted to an organization unit, this contains the ID for the organization unit the exercise of this role is restricted to.
	#' @param roleId The ID of the role that is assigned.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	roleAssignments.insert <- function(customer, assignedTo = NULL, kind = NULL, etag = NULL, roleAssignmentId = NULL, scopeType = NULL, orgUnitId = NULL, roleId = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.roleAssignments.insert']]$scopes), return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.roleAssignments.insert']], params = params)
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token))
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Retrieves a paginated list of all roleAssignments.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{make_google_package}}
	#'
	#' @seealso \href{http://developers.google.com/admin-sdk/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement
	#' \item https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
	#' }
	#' @param customer Immutable ID of the G Suite account.
	#' @param userKey The user's primary email address, alias email address, or unique user ID. If included in the request, returns role assignments only for this user.
	#' @param roleId Immutable ID of a role. If included in the request, returns only role assignments containing this role ID.
	#' @param maxResults Maximum number of results to return.
	#' @param pageToken Token to specify the next page in the list.
	#' @param gargle_token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(...) with appropriate scopes. See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	roleAssignments.list <- function(customer, userKey = NULL, roleId = NULL, maxResults = NULL, pageToken = NULL, gargle_token = gargle::token_fetch(scopes = .endpoints[['directory.roleAssignments.list']]$scopes), return_response = F){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('return_response', 'gargle_token')]
		req <- gargle::request_develop(endpoint = .endpoints[['directory.roleAssignments.list']], params = params)
		req <- gargle::request_build(method = req$method, path = req$path, params = req$params, body = req$body, token = httr::config(token = gargle_token))
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
