
	#' Gets information about the user, the user's Drive, and system capabilities.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.metadata
	#' \item https://www.googleapis.com/auth/drive.metadata.readonly
	#' \item https://www.googleapis.com/auth/drive.photos.readonly
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are appInstalled, canCreateDrives, canCreateTeamDrives, driveThemes, exportFormats, folderColorPalette, importFormats, kind, maxImportSizes, maxUploadSize, storageQuota, teamDriveThemes, user.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.about.get <- function(token = gargle::token_fetch(scopes = get_function_scopes('drive.about.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/about', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
