
	#' Creates a new comment on a file.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.file
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.comments.create <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.comments.create')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'drive/v3/files/{fileId}/comments', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Deletes a comment.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.file
	#' }
	#' @param fileId The ID of the file.
	#' @param commentId The ID of the comment.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.comments.delete <- function(fileId = NULL, commentId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.comments.delete')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'drive/v3/files/{fileId}/comments/{commentId}', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Gets a comment by ID.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param fileId The ID of the file.
	#' @param commentId The ID of the comment.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are anchor, author, content, createdTime, deleted, htmlContent, id, kind, modifiedTime, quotedFileContent, replies, resolved.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.comments.get <- function(fileId = NULL, commentId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.comments.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/files/{fileId}/comments/{commentId}', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Lists a file's comments.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are comments, kind, nextPageToken.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.comments.list <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.comments.list')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/files/{fileId}/comments', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Updates a comment with patch semantics.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.file
	#' }
	#' @param fileId The ID of the file.
	#' @param commentId The ID of the comment.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.comments.update <- function(fileId = NULL, commentId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.comments.update')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PATCH', path = 'drive/v3/files/{fileId}/comments/{commentId}', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
