
	#' Creates a copy of a file and applies any requested updates with patch semantics. Folders cannot be copied.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.photos.readonly
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.copy <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.copy')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'drive/v3/files/{fileId}/copy', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Creates a new file.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' }
	#' @param enforceSingleParent Deprecated. Creating files in multiple folders is no longer supported.
	#' @param ignoreDefaultVisibility Whether to ignore the domain's default visibility settings for the created file. Domain administrators can choose to make all uploaded files visible to the domain by default; this parameter bypasses that behavior for the request. Permissions are still inherited from parent folders.
	#' @param includePermissionsForView Specifies which additional view's permissions to include in the response. Only 'published' is supported.
	#' @param keepRevisionForever Whether to set the 'keepForever' field in the new head revision. This is only applicable to files with binary content in Google Drive. Only 200 revisions for the file can be kept forever. If the limit is reached, try deleting pinned revisions.
	#' @param ocrLanguage A language hint for OCR processing during image import (ISO 639-1 code).
	#' @param supportsAllDrives Whether the requesting application supports both My Drives and shared drives.
	#' @param supportsTeamDrives Deprecated use supportsAllDrives instead.
	#' @param useContentAsIndexableText Whether to use the uploaded content as indexable text.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.create <- function(enforceSingleParent = NULL, ignoreDefaultVisibility = NULL, includePermissionsForView = NULL, keepRevisionForever = NULL, ocrLanguage = NULL, supportsAllDrives = NULL, supportsTeamDrives = NULL, useContentAsIndexableText = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.create')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'drive/v3/files', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive the user must be an organizer on the parent. If the target is a folder, all descendants owned by the user are also deleted.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.delete <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.delete')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'drive/v3/files/{fileId}', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Permanently deletes all of the user's trashed files.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' }
	#' @param enforceSingleParent Deprecated. If an item is not in a shared drive and its last parent is deleted but the item itself is not, the item will be placed under its owner's root.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.emptyTrash <- function(enforceSingleParent = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.emptyTrash')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'DELETE', path = 'drive/v3/files/trash', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Exports a Google Doc to the requested MIME type and returns the exported content. Please note that the exported content is limited to 10MB.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param fileId The ID of the file.
	#' @param mimeType The MIME type of the format requested for this export.
	#' @param fields Selector specifying which fields to include in a partial response.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.export <- function(fileId = NULL, mimeType = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.export')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/files/{fileId}/export', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Generates a set of file IDs which can be provided in create or copy requests.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' }
	#' @param count The number of IDs to return.
	#' @param space The space in which the IDs can be used to create new files. Supported values are 'drive' and 'appDataFolder'.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are ids, kind, space.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.generateIds <- function(count = NULL, space = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.generateIds')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/files/generateIds', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Gets a file's metadata or content by ID.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.metadata
	#' \item https://www.googleapis.com/auth/drive.metadata.readonly
	#' \item https://www.googleapis.com/auth/drive.photos.readonly
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are appProperties, capabilities, contentHints, contentRestrictions, copyRequiresWriterPermission, createdTime, description, driveId, explicitlyTrashed, exportLinks, fileExtension, folderColorRgb, fullFileExtension, hasAugmentedPermissions, hasThumbnail, headRevisionId, iconLink, id, imageMediaMetadata, isAppAuthorized, kind, lastModifyingUser, md5Checksum, mimeType, modifiedByMe, modifiedByMeTime, modifiedTime, name, originalFilename, ownedByMe, owners, parents, permissionIds, permissions, properties, quotaBytesUsed, shared, sharedWithMeTime, sharingUser, shortcutDetails, size, spaces, starred, teamDriveId, thumbnailLink, thumbnailVersion, trashed, trashedTime, trashingUser, version, videoMediaMetadata, viewedByMe, viewedByMeTime, viewersCanCopyContent, webContentLink, webViewLink, writersCanShare.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.get <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.get')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/files/{fileId}', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Lists or searches files.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.metadata
	#' \item https://www.googleapis.com/auth/drive.metadata.readonly
	#' \item https://www.googleapis.com/auth/drive.photos.readonly
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param corpora Groupings of files to which the query applies. Supported groupings are: 'user' (files created by, opened by, or shared directly with the user), 'drive' (files in the specified shared drive as indicated by the 'driveId'), 'domain' (files shared to the user's domain), and 'allDrives' (A combination of 'user' and 'drive' for all drives where the user is a member). When able, use 'user' or 'drive', instead of 'allDrives', for efficiency.
	#' @param corpus The source of files to list. Deprecated: use 'corpora' instead.
	#' @param driveId ID of the shared drive to search.
	#' @param includeItemsFromAllDrives Whether both My Drive and shared drive items should be included in results.
	#' @param includePermissionsForView Specifies which additional view's permissions to include in the response. Only 'published' is supported.
	#' @param includeTeamDriveItems Deprecated use includeItemsFromAllDrives instead.
	#' @param orderBy A comma-separated list of sort keys. Valid keys are 'createdTime', 'folder', 'modifiedByMeTime', 'modifiedTime', 'name', 'name_natural', 'quotaBytesUsed', 'recency', 'sharedWithMeTime', 'starred', and 'viewedByMeTime'. Each key sorts ascending by default, but may be reversed with the 'desc' modifier. Example usage: ?orderBy=folder,modifiedTime desc,name. Please note that there is a current limitation for users with approximately one million files in which the requested sort order is ignored.
	#' @param pageSize The maximum number of files to return per page. Partial or empty result pages are possible even before the end of the files list has been reached.
	#' @param pageToken The token for continuing a previous list request on the next page. This should be set to the value of 'nextPageToken' from the previous response.
	#' @param q A query for filtering the file results. See the "Search for Files" guide for supported syntax.
	#' @param spaces A comma-separated list of spaces to query within the corpus. Supported values are 'drive', 'appDataFolder' and 'photos'.
	#' @param supportsAllDrives Whether the requesting application supports both My Drives and shared drives.
	#' @param supportsTeamDrives Deprecated use supportsAllDrives instead.
	#' @param teamDriveId Deprecated use driveId instead.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are files, incompleteSearch, kind, nextPageToken.
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.list <- function(corpora = NULL, corpus = NULL, driveId = NULL, includeItemsFromAllDrives = NULL, includePermissionsForView = NULL, includeTeamDriveItems = NULL, orderBy = NULL, pageSize = NULL, pageToken = NULL, q = NULL, spaces = NULL, supportsAllDrives = NULL, supportsTeamDrives = NULL, teamDriveId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.list')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'GET', path = 'drive/v3/files', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Updates a file's metadata and/or content. This method supports patch semantics.
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.metadata
	#' \item https://www.googleapis.com/auth/drive.scripts
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.update <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.update')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'PATCH', path = 'drive/v3/files/{fileId}', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}

	#' Subscribes to changes to a file
	#'
	#' Autogenerated via \code{\link[googlePackageMaker]{generate_google_package}}
	#'
	#' @seealso \href{https://developers.google.com/drive/}{Google Documentation}
	#'
	#' @details
	#' Authentication scopes used by this function are:
	#' \itemize{
	#' \item https://www.googleapis.com/auth/drive
	#' \item https://www.googleapis.com/auth/drive.appdata
	#' \item https://www.googleapis.com/auth/drive.file
	#' \item https://www.googleapis.com/auth/drive.metadata
	#' \item https://www.googleapis.com/auth/drive.metadata.readonly
	#' \item https://www.googleapis.com/auth/drive.photos.readonly
	#' \item https://www.googleapis.com/auth/drive.readonly
	#' }
	#' @param fileId The ID of the file.
	#' @param fields Selector specifying which fields to include in a partial response. Possible fields are .
	#' @param token A token prepared by one of gargle's token generating functions. Defaults to gargle::token_fetch(scopes = \code{\link[googlePackageMaker]{get_function_scopes}}(function_name). See \code{\link[gargle]{token_fetch}} for more info.
	#' @param return_response Whether to return the response or the response content. Defaults to FALSE (return response content).
	#' @export
	drive.files.watch <- function(fileId = NULL, token = gargle::token_fetch(scopes = get_function_scopes('drive.files.watch')), return_response = F, fields = NULL){
		params <- as.list(environment())[!names(as.list(environment())) %in% c('body', 'return_response', 'token')]
		req <- gargle::request_build(method = 'POST', path = 'drive/v3/files/{fileId}/watch', params = params, body = NULL, token = token, base_url = 'https://www.googleapis.com/')
		res <- gargle::request_make(req, encode = 'json')
		if(return_response) return(res)
		httr::content(res)
	}
